packages:
  - packages/authentication/*
  - packages/authentication/methods/*
  - packages/*
  - packages/nest/*
  - packages/pg-slonik/example
  - '!packages/authentication'
  - '!packages/authentication/methods'
  - '!packages/nest'

updateNotifier: false
