packages:
  - packages/authentication/*
  - packages/authentication/methods/*
  - packages/*
  - packages/nest/*
  - '!packages/authentication'
  - '!packages/authentication/methods'
  - '!packages/nest'

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - multiline-ts
  - simple-git-hooks
  - unrs-resolver

updateNotifier: false
