import '@rineex/ddd';

declare module '@rineex/ddd' {
  interface DomainErrorNamespaces {
    AUTH_CORE_MFA: [
      'CHALLENGE_ID_INVALID',
      'CHALLENGE_STATUS_INVALID',
      'CHALLENGE_EXPIRED',
      'EXPIRED',
      'ALREADY_VERIFIED',
      'ACTIVE_CHALLENGE_EXISTS',
      'ATTEMPTS_EXCEEDED',
      'SESSION_ID_INVALID',
    ];
    AUTH_CORE_TOKEN: ['INVALID'];
    AUTH_CORE_SCOPE: ['INVALID'];
    AUTH_CORE_SESSION: ['INVALID'];
    AUTH_CORE_ATTEMPT: ['AUTHENTICATION_FAILED', 'NOT_FOUND'];
    AUTH_CORE_IDENTITY: ['DISABLED_ERROR', 'INVALID_TRANSITION'];
    AUTH_CORE_OAUTH: [
      'INVALID_PROVIDER',
      'INVALID_REDIRECT_URI',
      'AUTHORIZATION_ALREADY_USED',
      'INVALID_PKCE',
      'INVALID_AUTHORIZATION_CODE',
      'CONSENT_REQUIRED',
      'AUTHORIZATION_EXPIRED',
    ];
    AUTH_OTP: ['AUTHENTICATION_FAILED'];
  }
}
