/**
 * HTTP status code catalog.
 *
 * This object provides a typed, immutable map of standard HTTP status names
 * to their numeric codes. Designed for server-side frameworks such as Fastify.
 *
 * - All identifiers use clear, canonical semantic names.
 * - Values are numeric status codes.
 * - Frozen to prevent runtime mutation.
 * - Exporting `HttpStatus` ensures type-safe usage across the codebase.
 */
export const HttpStatus = Object.freeze({
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  NON_AUTHORITATIVE_INFORMATION: 203,
  PROXY_AUTHENTICATION_REQUIRED: 407,

  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  BANDWIDTH_LIMIT_EXCEEDED: 509,
  VARIANT_ALSO_NEGOTIATES: 506,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  PRECONDITION_REQUIRED: 428,
  INTERNAL_SERVER_ERROR: 500,
  UNPROCESSABLE_ENTITY: 422,
  INSUFFICIENT_STORAGE: 507,

  SWITCHING_PROTOCOLS: 101,
  PRECONDITION_FAILED: 412,
  MISDIRECTED_REQUEST: 421,
  SERVICE_UNAVAILABLE: 503,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  METHOD_NOT_ALLOWED: 405,
  EXPECTATION_FAILED: 417,

  MOVED_PERMANENTLY: 301,
  PAYLOAD_TOO_LARGE: 413,
  FAILED_DEPENDENCY: 424,
  TOO_MANY_REQUESTS: 429,
  ALREADY_REPORTED: 208,
  MULTIPLE_CHOICES: 300,
  PAYMENT_REQUIRED: 402,
  UPGRADE_REQUIRED: 426,
  PARTIAL_CONTENT: 206,
  REQUEST_TIMEOUT: 408,
  LENGTH_REQUIRED: 411,
  NOT_IMPLEMENTED: 501,
  GATEWAY_TIMEOUT: 504,
  NOT_ACCEPTABLE: 406,
  RESET_CONTENT: 205,
  LOOP_DETECTED: 508,
  MULTI_STATUS: 207,
  NOT_MODIFIED: 304,
  UNAUTHORIZED: 401,
  URI_TOO_LONG: 414,
  NOT_EXTENDED: 510,
  EARLY_HINTS: 103,
  BAD_REQUEST: 400,
  IM_A_TEAPOT: 418,
  BAD_GATEWAY: 502,
  PROCESSING: 102,
  NO_CONTENT: 204,
  SEE_OTHER: 303,
  USE_PROXY: 305,

  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_EARLY: 425,
  CONTINUE: 100,
  ACCEPTED: 202,
  CONFLICT: 409,
  CREATED: 201,
  IM_USED: 226,
  LOCKED: 423,
  FOUND: 302,
  GONE: 410,
  OK: 200,
} as const);

/**
 * HTTP status messages mapped by numeric code.
 * Use for sending descriptive text in responses or logging.
 */
export const HttpStatusMessage = {
  431: 'Request Header Fields Too Large',
  511: 'Network Authentication Required',
  203: 'Non-Authoritative Information',
  407: 'Proxy Authentication Required',
  451: 'Unavailable For Legal Reasons',
  505: 'HTTP Version Not Supported',
  509: 'Bandwidth Limit Exceeded',
  506: 'Variant Also Negotiates',
  415: 'Unsupported Media Type',
  416: 'Range Not Satisfiable',
  428: 'Precondition Required',
  500: 'Internal Server Error',
  422: 'Unprocessable Entity',
  507: 'Insufficient Storage',
  101: 'Switching Protocols',
  412: 'Precondition Failed',
  421: 'Misdirected Request',
  503: 'Service Unavailable',
  307: 'Temporary Redirect',
  308: 'Permanent Redirect',
  405: 'Method Not Allowed',
  417: 'Expectation Failed',
  301: 'Moved Permanently',
  413: 'Payload Too Large',
  424: 'Failed Dependency',
  429: 'Too Many Requests',
  208: 'Already Reported',
  300: 'Multiple Choices',
  402: 'Payment Required',
  426: 'Upgrade Required',
  206: 'Partial Content',
  408: 'Request Timeout',
  411: 'Length Required',
  501: 'Not Implemented',
  504: 'Gateway Timeout',
  406: 'Not Acceptable',
  205: 'Reset Content',
  508: 'Loop Detected',
  207: 'Multi-Status',
  304: 'Not Modified',
  401: 'Unauthorized',
  414: 'URI Too Long',
  418: "I'm a Teapot",
  510: 'Not Extended',
  103: 'Early Hints',
  400: 'Bad Request',
  502: 'Bad Gateway',
  102: 'Processing',
  204: 'No Content',
  303: 'See Other',
  305: 'Use Proxy',
  403: 'Forbidden',
  404: 'Not Found',
  425: 'Too Early',
  100: 'Continue',
  202: 'Accepted',
  226: "I'm Used",
  409: 'Conflict',
  201: 'Created',
  423: 'Locked',
  302: 'Found',
  410: 'Gone',
  200: 'OK',
} as const;

export type HttpStatusCode = keyof typeof HttpStatusMessage;

export type HttpStatusMessage =
  (typeof HttpStatusMessage)[keyof typeof HttpStatusMessage];
